# Numpy = (fast) numerical Python

https://www.numpy.org says:
> NumPy is the fundamental package for scientific computing with Python. It contains among other things:
> 
> * a powerful N-dimensional array object
> * sophisticated (broadcasting) functions
> * tools for integrating C/C++ and Fortran code
> * useful linear algebra, Fourier transform, and random number capabilities

Some parts, especially images, are adopted from https://jalammar.github.io/visual-numpy/.

## Why Numpy?

Because numerics using only Python standard library is cumbersome and in most cases slow.

In [1]:
import numpy as np

In [2]:
np.version.full_version

'1.19.4'

## Creating Numpy arrays

The most used type in Numpy is `np.ndarray`, which is often created by the [`np.array`](https://numpy.org/doc/1.19/reference/generated/numpy.array.html) function.

In [3]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

![create-numpy-array-1.png](images/numpy/create-numpy-array-1.png)

In [4]:
type(array)

numpy.ndarray

Unlike built-in containers like `list`s, `np.ndarray`s have
* homogeneous `dtype`(s) (data types)

In [5]:
array.dtype

dtype('int64')

* fixed `shape` (dimensions)

In [6]:
array.shape

(3,)

**Exercise:** Can you fill the missing values (by replacing `...`) to make the `assert`s pass (i.e. no `AssertException` raised)?

In [7]:
test_array = np.array([[1.9, 2.8], [3.7, 4.5]])
test_array

array([[1.9, 2.8],
       [3.7, 4.5]])

In [8]:
test_array_shape = ...
test_array_dtype = ...

In [9]:
assert test_array.shape == test_array_shape
assert test_array.dtype == test_array_dtype

AssertionError: 

Arrays can be created using helper constructors, such as `empty`, `zeros`, `arange`, `linspace`, `diag`, ...

In [ ]:
np.zeros((2, 8), dtype=float)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

### Supported dtypes

- boolean 
- integers (8-, 16-, 32-, 64-bit), unsigned / signed
- float (32-, 64-bit)
- complex
- fixed-length strings (byte / unicode)
- object (reference to any Python object)
- structured types (with more fields)

For more details, see https://numpy.org/doc/stable/user/basics.types.html.

In [ ]:
# this will create an array of unicode, fixed length strings
string_array = np.array(["a", "å", "aardvark", "abe"])
string_array.dtype

dtype('<U8')

In [ ]:
string_array

In [ ]:
# objects can be anything
objects_array = np.array(["a", "å", "aardvark", 100, -1.2e-3, []], dtype="object") 
objects_array.dtype

In [ ]:
objects_array

## Indexing

Numpy supports enhanced indexing compared e.g. to Python's `list` or `array` types. Especially:
* multiple dimensions
* enhaced slices
* "advanced" or "fancy" indexing using arrays

In [ ]:
array_1d = np.arange(1, 10)
array_1d

![numpy-array-slice.png](images/numpy/numpy-array-slice.png)

### Basic indexing 

Basic indexing and slicing on 1D array works identically to lists:

In [ ]:
array_1d[5]

In [ ]:
array_1d[5: -1]

In [ ]:
array_1d[::-3]

**Exercise:** Fill the slicing to satisfy the assert test. Notice we have to use `np.all` because the result is an array which cannot be converted to a single boolean value unambigously (is a true and false couple true or false?).

In [ ]:
result = array_1d[...]

In [ ]:
assert np.all(result == np.array([1, 5, 9]))

*Extra question:* Did you notice that (and how) the ellipsis slice `[...]` actually work?

Multi-dimensional arrays can be index conveniently:

In [ ]:
array_2d = np.random.randint(0, 10, (2, 6))
array_2d

In [ ]:
array_3d = array_2d.reshape(2, -1, 3)
array_3d

Single index returns a slice in one dimension:

In [ ]:
array_2d[1]

Which is equivalent to:

In [ ]:
array_2d[1, :]

And also

In [ ]:
array_2d[1, ...]

Examples for 3-D array:

In [ ]:
array_3d[:, 0, 1:]

In [ ]:
array_3d[..., -1]

### Fancy indexing

Suppose you need to access particular elements, say `3, 0, 5`. Instead of something like `np.array([array_1d[3], array_1d[0], array_1d[5]])`, you can write

In [ ]:
array_1d[[3, 0, 5]]

**Exercise:** Use (fancy) indexing to create a 8 x 8 chess-board pattern (0 / 1 in place of white / black) from a uniform array.

In [ ]:
chess_board = np.ones((8, 8), dtype=int)

chess_board[..., ...] = ...
chess_board[..., ...] = ...

# display
chess_board

In [ ]:
assert np.all(chess_board == np.tile([[1, 0], [0, 1]], (4, 4)))

Another possibility is to use arrays of boolean values for slicing.

In [ ]:
bool_indexes = np.zeros_like(array_1d, dtype=bool)
bool_indexes[[2, 5]] = True
bool_indexes

In [ ]:
array_1d[bool_indexes]

### Indexing vs. copying

Indexing in `numpy` does not have to create copies. Data copy is created only when inevitable.

Hence, **modyfying a slice can modify the original array**.

In [ ]:
original_array = np.linspace(0, 1, 3)
original_array

In [ ]:
array_slice = original_array[1: ]
array_slice *= 2
array_slice

In [ ]:
original_array

See that??? The original array has been modified.

## Vector operations

Numpy is optimized for performance. One of the key ingredient are vectorized operations: Instead of (slow) looping by elements, an operation can be performed on the whole or at least a subset of an array.

Let's try to implement a dot product (1D for simplicity):

In [ ]:
def dot(x, y):
    result = 0
    for i, j in zip(x, y):
        result += i * j
    
    return result

In [ ]:
x = np.random.sample((4, ))
y = np.random.sample((4, ))

dot(x, y)

Test our function using `allclose` to compare floats only up to certain precision.

In [ ]:
assert np.allclose(dot(x, y), x.dot(y))

We can compare the performance (on larger arrays)

In [ ]:
size = (1000, )
x_large = np.random.sample(size)
y_large = np.random.sample(size)

In [ ]:
%timeit dot(x_large, y_large)

In [ ]:
%timeit x_large.dot(y_large)

Even multiplication (`*` is element-wise in Numpy) is vectorized. E.g.:

In [ ]:
x * y

**Exercise:** Implement dot using `*` and `sum` and measure its performace using `%timeit`.

In [ ]:
def dot_2(x, y):
    return(___).___()

In [ ]:
assert np.allclose(dot_2(x, y), x.dot(y))

In [ ]:
%timeit dot_2(x_large, y_large)

Bottom line: use numpy functions and operations because they are vectorized and hence (in most cases) faster.

## Aggregation

Aggregate function turn multiple values (vector elements, columns, matrices, ...) into a single value.
Typical examples are minimum, sum, product or mean. 
Boolean `all` or `any`, which we have seen already, are also aggregations.

In Numpy, aggregation is performed as an `ndarray` method call or via a function call.

Aggregations in Numpy operate on whole arrays by default, for 1-D (vectors), 2-D (matrices) or more-D arrays
![](images/numpy/numpy-array-aggregation.png)
![](images/numpy/numpy-matrix-aggregation-1.png)


In [ ]:
# let's try some aggregations and a random sample
random_data = np.random.random_sample((3, 300))

random_data.sum()

We can also aggregate along a given axis only by using the `axis` parameter.
![](images/numpy/numpy-matrix-aggregation-2.png)

In [ ]:
random_data.sum(axis=1)

## Resize & reshape

Sometimes, the elements of your arrays are ok, but their shape is not
(e.g. you read a linear series of pixel values, knowing they form
a two-dimensional image with three channels). To reinterpret the data
with a new shape, use the [`reshape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html) method:



In [15]:
data = np.arange(1, 7)
data

array([1, 2, 3, 4, 5, 6])

![](images/numpy/numpy-reshape.png)

In [16]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Note: `reshape` just takes the data as a linear array and applies the shape on it.
So when reshaping an array multiple times, only "the last counts":

In [21]:
data.reshape(3, 2).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

If you are lazy to calculate the exact shape, you may omit one of the dimensions and give `-1`
in its place - it gets computed for you:

In [22]:
data.reshape(3, -1)  # "Guesses" the right dim is 2

array([[1, 2],
       [3, 4],
       [5, 6]])

You might have spotted that the two 2x3 arrays are not transpose of each other.
To do so, you may want to use the [`transpose`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html)
method (or equivalently, the `T` property):

In [24]:
data.reshape(3, -1).transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [25]:
data.reshape(3, -1).T

array([[1, 3, 5],
       [2, 4, 6]])

## Broadcasting

Numpy automatically broadcasts (aligns / enhances the dimensions) of arrays if it "makes sense" 
(there are strict rules :). Broadcasting simplifies operations and can make them faster 
and / or less memory consuming.
The memory consumption can, however, increase when using broadacasting as well.
This is because short-lived helper arrays are created in the memory during broadcasting.

An example is to substract the column mean from an $n \times m$ array.

In [ ]:
X = np.linspace(0, 1, 15).reshape(-1, 3)
X

In [ ]:
X.mean(axis=0)

Now we'd like to center the columns around zero, i.e. make the mean = 0 of all columns.

In [ ]:
X_centered = X - X.mean(axis=0)

In [ ]:
X_centered.mean(axis=0)

We can also do this explicitely with `newaxis`

In [ ]:
X_centered = X - X.mean(axis=0)[np.newaxis, :]

**Exercise:** Calculate $uv$ for random 1D arrays $u$ and $v$, defined as $(uv)_{ij} = u_i v_j$, using broadcasting.

In [ ]:
u = np.random.sample((3, ))
v = np.random.sample((5, ))

uv = u[...] * v[...]

In [ ]:
for i, j in zip(range(u.size), range(v.size)):
    assert uv[i, j] == u[i] * v[j]

## Under the hood: the buffer protocol

`ndarray` data are stored in (typically) contiguous memory blocks. This is for performance reasons because Numpy can employ fast C libraries (like BLAS) for vectorized operations without converting and / or rearranging the data in the memory. Python offers built-in [Buffer Protocol](https://docs.python.org/3/c-api/buffer.html#bufferobjects) which standardizes this approach and enables (relatively) easy integration with C libraries.

In a nutshell, `ndarray` data are described by their memory buffer location (pointer), and some metedata mainly describing the data type (`typestr`) and dimensionality (`shape` and `strides`).

Looking a bit under the hood, we can see the buffer info by `info` or `flags`

In [ ]:
np.info(array)

In [ ]:
array.flags

This is an implementation detail, although very important because it determines fundamental advantages, limitations and best practices for using `numpy`.

### Further reading

- [NumPy official documentation](https://numpy.org/doc/)
- [NumPy tutorial @ realpython.com](https://realpython.com/numpy-tutorial/)
- [100 NumPy Exercises](https://github.com/rougier/numpy-100)